services:
  note_postgres:
    image: postgres:17
    container_name: ${NOTE_POSTGRES}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${NOTE_DB}
    ports:
      - "5433:5432"
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - ./note_service/db/init:/docker-entrypoint-initdb.d
    networks: [backend]

networks:
  backend:
    driver: bridge
    external: true
