services:
  note_service:
    container_name: note_service
    build:
      context: ./note_service
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    networks: [backend]

  user_service:
    container_name: user_service
    build:
      context: ./user_service
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    networks: [backend]

networks:
  backend:
    driver: bridge
    external: true
