CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE notes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
  user_id UUID,
  type_id UUID,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ended_at TIMESTAMP,
  completed BOOLEAN DEFAULT FALSE
);

